### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by SerhiiYanchuk** [SerhiiYanchuk/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by ghost** [comment]
<h2>Resume</h2>
<p>Логика – это искусство ошибаться с уверенностью в своей правоте.</p>
<p>&mdash; Джозеф Крач</p>
<p>*Instagram активно не веду, то хоть тут цитату оставлю</p>

**Comment by SerhiiYanchuk** [comment]
Жиза

> ## Resume
> Логика – это искусство ошибаться с уверенностью в своей правоте.
> 
> — Джозеф Крач
> 
> *Instagram активно не веду, то хоть тут цитату оставлю
